objects/Product2.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>AverageRating__c</fullName>
        <label>AverageRating</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Review__c.object
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>RE-{000}</displayFormat>
        <label>Review No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/ProductReviewController.cls
public class ProductReviewController {
  public Product2 product;
  public Review__c review { get; set; }
  public ProductReviewController(ApexPages.StandardController controller) {
    product = (Product2) controller.getRecord();
    review = new Review__c(Product__c=product.Id);
  }
  public void saveReview() {
    insert review;
    // update product average rating
    List<Review__c> reviews = [SELECT Rating__c FROM Review__c WHERE Product__c=:product.Id];
    if (reviews.size() > 0) {
      Decimal totalRating = 0;
      for (Review__c r : reviews) {
        totalRating += Integer.valueOf(r.Rating__c);
      }
      Decimal avgRating = totalRating / reviews.size();
      product.AverageRating__c = avgRating;
      update product;
    }
  }
}